#!/bin/bash

input=$1
output=$2
min_read=$3
binSize=$4
thread=$5
GENOMESIZES=$6

# usage info
if [[ -z ${input} ]]; then
	echo "Usage: "
	echo -e "\t\$1: input, the bismark output file, such as '\${prefix}.deduplicated.bismark.cov.gz'"
	echo -e "\t\$2: output, the output bigwig file name."
	echo -e "\t\$3: min_read, the minimum of **total** reads in input file. default 0 (not filter)."
	echo -e "\t\$4: binSize, default 50"
	echo -e "\t\$5: thread, default 10"
	echo -e "\t\$6: GENOMESIZES, default $HOME/Program/S3V2_IDEAS_ESMP/genomesize/hg38.chrom.1_22XY.sizes"
	exit 100
fi


# default setting
if [[ -z ${min_read} ]]; then
	min_read=0
fi

if [[ -z ${binSize} ]]; then
	binSize=50
fi

if [[ -z ${thread} ]]; then
	thread=10
fi

if [[ -z ${GENOMESIZES} ]]; then
	GENOMESIZES=$HOME/Program/S3V2_IDEAS_ESMP/genomesize/hg38.chrom.1_22XY.sizes
fi


# filter data and get methy and all C reads
zcat ${input} | awk -F "\t" -v OFS="\t" -v cutoff=${min_read} '{if($5+$6 > cutoff) {print $1,$2-1,$3,$5}}' > ${input}.methy.bedgraph
zcat ${input} | awk -F "\t" -v OFS="\t" -v cutoff=${min_read} '{if($5+$6 > cutoff) {print $1,$2-1,$3,$5+$6}}' > ${input}.total.bedgraph


# get redundent bed and transfer to bam
echo -e "methy\ntotal" | xargs -n1 -i -P 2 bed2bam ${input}.{}.bedgraph ${input}.{}.bam ${GENOMESIZES}
echo -e "methy\ntotal" | xargs -n1 -i -P 2 samtools index -@ ${thread} ${input}.{}.bam


# transfer to standard bigwig file format
echo -e "methy\ntotal" | xargs -n1 -i -P 2 \
	bamCoverage --bam ${input}.{}.bam \
	--outFileName ${input}.{}.bw \
	--outFileFormat bigwig --binSize ${binSize} \
	--numberOfProcessors ${thread} 1>/dev/null 2>&1


# get normalization
bigwigCompare --bigwig1 ${input}.methy.bw --bigwig2 ${input}.total.bw \
	--scaleFactors 1:0.01 \
	--operation ratio --pseudocount 0 \
	--binSize ${binSize} \
	-p ${thread} \
	--outFileName ${output}

# remove redundent files
rm ${input}.methy.* ${input}.total.*

echo "${input} has been transfer to normalized bigwig format successfully"

