#!/bin/bash

if [[ -z $1 ]]; then
	echo "Usage: "
	echo -e "\t\$1: The input read count matrix file, such as multiBigwigSummary_bs200.tab."
	echo -e "\t\$2: The file recording required data name label."
	echo -e "\t\$3: The output filename."
	exit 100
fi

tab=$1
name=$2
output=$3

script=/share/home/fatyang/Program/Custom_tools/deeptools_corTAB_split.R
Rscript ${script} ${tab} ${name} ${output}
