#!/bin/bash

input=$1

if [[ -z ${input} ]]; then
	echo "Usage: "
	echo "The ASCII Correspondence:"
	cat $HOME/Database/Tamplate/3.ASCII/ASCII.txt
	echo "The coding relationship:"
	cat $HOME/Database/Tamplate/3.ASCII/Phred.txt
	echo -e "\nUsage: "
	echo -e "\t\$1: input fq.gz file."
	exit 100
fi

zcat $1 | head -n 1000 | awk '{if(NR%4==0) printf("%s",$0);}' | \
	od -A n -t u1 -v | awk 'BEGIN{min=100;max=0;} \
	{for(i=1;i<=NF;i++) {if($i>max) max=$i; if($i<min) min=$i;}} \
	END {if(max<=74 && min<59) print "Phred+33"; \
	else if(max>73 && min>=64) print "Phred+64"; \
	else if(min>=59 && min<64 && max>73) print "Solexa+64"; \
	else print "Unknown score encoding"; \
	print "(" min ", " max ")" }'

echo -e "\nReference:"
cat $HOME/Database/Tamplate/3.ASCII/Phred.txt
