#!/bin/bash
# Name: ideas_bedgraph2bw

# manual:
#   IDEAS output bedgraph file to standard bigwig file (200bp bin size and remove blacklist region)
#
#   ideas_bedgraph2bw bedgraph bigwig windows GENOMESIZES
#	 - bedgraph: the input bedgraph file
#	 - bigwig: the output bigwig file
#	 - windows: the windows file, 200bp bin size and remove blacklist region (windowsNoBlack.noid.bed)
#	 - GENOMESIZES: the Genome size file (hg38.chrom.1_22XY.sizes)
#
# For example:
#   ideas_bedgraph2bw H2AFZ.bedgraph H2AFZ.bw windowsNoBlack.noid.bed hg38.chrom.1_22XY.sizes
#
# Output:
#   - H2AFZ.bw: the bigwig file, 200bp bin size without blacklist region

bedgraph=$1
bigwig=$2
windows=$3
GENOMESIZES=$4

if [[ -z ${bedgraph} ]]; then
	echo "Usage: "
	echo -e "\t\$1: input bedgraph"
	echo -e "\t\$2: output bigwig"
	echo -e "\t\$3: 200bp size window file. You can search in $HOME/Database/S3V2_Genome_windows/1.human/1.hg38/1.bin200 directory."
	echo -e "\t\tdefault: $HOME/Database/S3V2_Genome_windows/1.human/1.hg38/1.bin200/windowsNoBlack.noid.bed"
	echo -e "\t\$4: GENOMESIZES file, You can search in $HOME/Program/S3V2_IDEAS_ESMP/genomesize directory."
	echo -e "\t\tdefault: $HOME/Program/S3V2_IDEAS_ESMP/genomesize/hg38.chrom.1_22XY.sizes"
	exit 100
fi

if [[ -z ${windows} ]]; then
	windows=$HOME/Database/S3V2_Genome_windows/1.human/1.hg38/1.bin200/windowsNoBlack.noid.bed
fi

if [[ -z ${GENOMESIZES} ]]; then
	GENOMESIZES=$HOME/Program/S3V2_IDEAS_ESMP/genomesize/hg38.chrom.1_22XY.sizes
fi


fid=$(basename ${bedgraph})
tmp=$HOME/tmp/UCSC/bedGraphToBigWig/${fid}

if [[ ! -d ${tmp} ]]; then
	mkdir -p ${tmp}
fi

paste ${windows} ${bedgraph} | sort -k1,1 -k2,2n - > ${tmp}/tmp
bedGraphToBigWig ${tmp}/tmp ${GENOMESIZES} ${bigwig}

rm -rf ${tmp}

