#!/bin/bash

# modify

command=$1

if [[ -z ${command} ]]; then
	echo "Usage: modify \$command"
	exit 100
fi

if [[ -f ${command} ]]; then
	path=$(which ${command})
else
	path=$HOME/Program/Custom_tools/${command}
fi

vim ${path}
