#!/bin/bash

# get arguments
account=$1
passwd=$2
output_dir=$3
pattern=$4
thread=$5

if [[ -z ${account} ]]; then
    echo "Usage: "
    echo -e "\t\$1: account，账户"
    echo -e "\t\$2: passwd，密码"
    echo -e "\t\$3: output_dir，输出目录"
    echo -e "\t\$4: pattern, 'raw' or 'clean'，或者其他可用于搜索的unique关键词，推荐使用marker信息，忽略大小写"
    echo -e "\t\$5: thread, default 1"
    exit 100
fi

if [[ ${pattern} == "clean" ]]; then
    pattern="00.CleanData"
elif [[ ${pattern} == "raw" ]]; then
    pattern="01.RawData"
fi

if [[ -z ${thread} ]]; then
    thread=1
fi

rand=$RANDOM
now=$(date "+%Y%m%d")
tmp=$HOME/tmp/novogene_download/${now}
mkdir -p ${tmp}
echo "Target Diectory: ${tmp}" > status.log.txt

# login in
lnd login -u ${account} -p ${passwd}

# get id
lnd list 1>${tmp}/all_file.${rand}.txt 2>&1
if [[ $? -ne 0 ]]; then
    rm -rf ${tmp}/all_file.${rand}.txt
    echo "Login wrong"
    exit 100
fi
root=$(cat ${tmp}/all_file.${rand}.txt)

# get all files
lnd list ${root} 1>${tmp}/all_file.${rand}.txt 2>&1
egrep -i "${pattern}" ${tmp}/all_file.${rand}.txt | cut -f3 > ${tmp}/fileFullPathName.${rand}.txt
cat ${tmp}/fileFullPathName.${rand}.txt | xargs dirname | xargs basename -a > ${tmp}/fileDirName.${rand}.txt
sort -u ${tmp}/fileDirName.${rand}.txt > ${tmp}/unique_FileDirName.${rand}.txt

# download raw data
# {} ${tmp}/fileDirName.${rand}.txt: 根据{}名字匹配${tmp}/fileDirName.${rand}.txt中服务器文件排名
# ${tmp}/fileFullPathName.${rand}.txt: server file path，根据排名提取目的文件
# ${output_dir}/{}: output directory，将文件下载到指定目录中保存

cat ${tmp}/unique_FileDirName.${rand}.txt | xargs -n1 -i -P ${thread} \
    novogene_download_dir {} ${tmp}/fileDirName.${rand}.txt \
    ${tmp}/fileFullPathName.${rand}.txt \
    ${output_dir}/{} ${root} 3 ${tmp}

# check download status
ls -l ${tmp} | egrep "^d" 1>/dev/null 2>&1
if [[ $? -eq 0 ]]; then
    echo "The following files failed to download:" >> status.log.txt
    ls -d ${tmp}/*/ >> status.log.txt
else
    echo "All files are downloaded successfully." >> status.log.txt
fi
