#!/bin/bash

# Manual
#   print difference set, file1-file2
#
# Usage:
#   setdiff file1 file2
#
# Options:
#   - file1/2: the input fiile, which has only one column.
#
# Output:
#   print stdout on the screen the difference between two sets

file1=$1
file2=$2

if [[ -z ${file1} ]]; then
	echo "Usage: result=reference-target"
	echo -e "\t\$1: The reference file"
	echo -e "\t\$2: The target file"

	exit 100
fi

sort ${file1} ${file2} ${file2} | uniq -u
