#!/bin/bash

if [[ -z $1 ]]; then
	echo "Usage: get the all unique results of File1+File2: unique(File1-File2)"
	echo -e "\t\$1: File1"
	echo -e "\t\$2: File2"

	exit 100
fi

file1=$1
file2=$2

sort ${file1} ${file2} | uniq
