#!/bin/bash

# 6. srp2srr
id=$1

if [[ -z $id ]]; then
	echo "Usage: "
	echo -e "\t\$1: The SRP ID."
	exit 100
fi

echo ${id} | egrep -i "^SRP" 1>/dev/null 2>&1
if [[ $? -ne 0 ]]; then
	echo "$id is not a SRP ID, please check."
	exit 100
fi


# environment preparion
if [[ ${CONDA_DEFAULT_ENV} != "sra" ]]; then
	eval "$(micromamba shell hook --shell=bash)"
	micromamba activate sra
fi

pysradb srp-to-srr ${id^^}

