#!/bin/bash

# 8. srr2srp
id=$1

if [[ -z $id ]]; then
	echo "Usage: "
	echo -e "\t\$1: The SRR ID."
	exit 100
fi

echo ${id} | egrep -i "^SRR" 1>/dev/null 2>&1
if [[ $? -ne 0 ]]; then
	echo "$id is not a SRR ID, please check."
	exit 100
fi


# environment preparion
if [[ ${CONDA_DEFAULT_ENV} != "sra" ]]; then
	eval "$(micromamba shell hook --shell=bash)"
	micromamba activate sra
fi

pysradb srr-to-srp ${id^^}

